# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    sudo apt-get install qemu-system-arm expect
    qemu-system-arm --version
    uname -a
    pwd
    wget https://public.am.files.1drv.com/y4mxbWKzbwgtgOqjOoOXmF6jJHdWYiM3HXkQfVotMDXKP11T0tJv_GCRUOX_rqHDrafVRgmDKgXSX2_ttJym90bAW5kp90lY8bwmU2aIFqzrljUgMrHTzdSyWKPEp9T4HT1f9xyHBoJQXuwvVyyomGNVJgj5CgVBKk2mwKmHCh0HINxJiJWnsMoCJJuqPObjyKj2JYBTr9oWMtk_mD4-XW-3IcPl-SVKvH1-2XouZfRzU0?access_token=EwAwA61DBAAUzl/nWKUlBg14ZGcybuC4/OHFdfEAAcFfiKp1r6lOJ3oT7NLBeiDp4LO9ic2bQrYg7Q62kGaYSVXwDCskNWE2iJPDZpOSO6%2bCSNfLzd0FjB69GFqnnMtF2N8sLjdfcbRPX/oOPiueAlIbSCFz39qNhqPhvlGJjZ5ruXpvouCGji%2bby7720mrA5%2bZHRr84QHMZEiu6XPo3V/SsRf0HnFHXvv2nr6VzNMhJqlf1igBIRHlfw2OqYTGI3ZCTyE5TF0o1Q%2bjBXCdoofrpNFSRbkvzDAi%2bzCJqQHNvxeOxfl202s1osQs2rb6o1uWW3f5InUDrrNy644qXTRTSpEHvD8ddBWsQQDewVUxyBNW/5QkOHAPGVJ/7jIUDZgAACOAHh36oJfdVAAIrgM77e0p%2bl9xa07Ou3d/dXqpcOrKtrPSZ6DHK5XZlyIA3UQuZQmQiUqMl23FX4e7ePxRTkA0%2bmyjFoW/HhTolOaWfymDPoa0B6VFO6ZQtgnhJJ4N12iFZRdUacK1Xe3WWPa3Pf7oljsnOEf3y2%2bHmMOQhky8zJiMbRW6q5eCxJnloI7Ew4zo1jF6eERchbhwz49QP3qIfDiCmD0SMesFtCYOoHcQxrwS47NtgGopyDZX2ZdS6XL%2bYbXV/v5KnaSUniin4sJpqA251oBy9nuRd1zour/v1CWYoe8zK9NXuC%2bq58Mi2nofF9nsSh/lONXr1YPJlGUzpiwFDrNadG7K2MJHfkQdOvVhlFDKVUpwPiqviIb9czI7bkrqn988lehSMVzoQOLKxzEaX%2by%2bFYaoVx9Emw9KpleIm17ut7xTNNpLF7VAwAh5cG0W9qFznO0ZvmrH8lM5eqngO7hxayYkgyPaVINNvcYiP/Y169rIu%2b2DU0F%2bMdHopsuiFDeYr1WfTpXQOFIFSjuLBhtzTtewA4zUv%2bTQziHJEo5s2PLm6qVq9LNCvTjosZJ3VODnGUwZI4N8I/htl6bRiZ7DhLI17VIbOeFM39L6cjxVz8PAv99VcmFEMTf7A0Tqyq5bqxtsC%2bzAFAN9Dm7CPLksZ6%2b8i9qL0F7QWoTSOGuav4ALKegUC -O raspiqemu.zip
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
